import { ISOStandard, TrainingCourse, DocumentItem, OfficeLocation, CertificateData } from "@/types";

export const ISO_STANDARDS: ISOStandard[] = [
  {
    id: "iso-9001",
    code: "ISO 9001:2015",
    name: "Quality Management Systems (QMS)",
    shortName: "QMS ISO 9001",
    category: "Quality & Operations",
    description: "International benchmark for operational consistency, customer satisfaction, and process improvement.",
    outcome: "Boost operational efficiency, client trust & global market access.",
    clauseChip: "§ 4–10 HLS",
    iconName: "ShieldCheck",
    featured: true,
  },
  {
    id: "iso-14001",
    code: "ISO 14001:2015",
    name: "Environmental Management Systems (EMS)",
    shortName: "EMS ISO 14001",
    category: "Health & Environment",
    description: "Framework for strategic environmental performance, regulatory compliance, and waste reduction.",
    outcome: "Reduce environmental footprint, regulatory risk & resource waste.",
    clauseChip: "§ 4–10 HLS",
    iconName: "Leaf",
    featured: true,
  },
  {
    id: "iso-22000",
    code: "ISO 22000:2018",
    name: "Food Safety Management Systems (FSMS)",
    shortName: "FSMS ISO 22000",
    category: "Quality & Operations",
    description: "Combines Codex HACCP principles with prerequisite programs for end-to-end food chain safety.",
    outcome: "Ensure food product integrity & legal compliance across supply chains.",
    clauseChip: "HACCP + PRPs",
    iconName: "Utensils",
  },
  {
    id: "iso-27001",
    code: "ISO/IEC 27001:2022",
    name: "Information Security Management System (ISMS)",
    shortName: "ISMS ISO 27001",
    category: "Information Security & Privacy",
    description: "Updated 2022 edition with 93 controls & 4 themes for cyber resilience and threat management.",
    outcome: "Protect critical data assets, achieve cyber resilience & client compliance.",
    clauseChip: "93 Controls · 4 Themes",
    iconName: "Lock",
    badge: "Updated 2022",
    featured: true,
  },
  {
    id: "iso-27701",
    code: "ISO/IEC 27701:2019",
    name: "Privacy Information Management System (PIMS)",
    shortName: "PIMS ISO 27701",
    category: "Information Security & Privacy",
    description: "Privacy extension to ISO 27001/27002 for PII Controllers and Processors with GDPR mapping.",
    outcome: "Demonstrate GDPR, DPA & global privacy regulation compliance.",
    clauseChip: "GDPR Annex A–F",
    iconName: "UserCheck",
  },
  {
    id: "iso-45001",
    code: "ISO 45001:2018",
    name: "Occupational Health & Safety (OH&S)",
    shortName: "OH&S ISO 45001",
    category: "Health & Environment",
    description: "Proactive framework for workplace safety, injury prevention, and worker health management.",
    outcome: "Eliminate hazard risks, reduce absenteeism & safeguard workforce.",
    clauseChip: "§ 4–10 HLS",
    iconName: "Activity",
    featured: true,
  },
  {
    id: "iso-20000-1",
    code: "ISO/IEC 20000-1:2018",
    name: "IT Service Management Systems (ITSMS)",
    shortName: "ITSMS ISO 20000-1",
    category: "IT Services",
    description: "Aligns IT services with business objectives across the complete service lifecycle (Plan → Deliver).",
    outcome: "Elevate IT service reliability, SLA compliance & customer satisfaction.",
    clauseChip: "Service Lifecycle",
    iconName: "Server",
  },
];

export const COURSES: TrainingCourse[] = [
  {
    id: "lead-auditor-27001",
    standardCode: "ISO 27001:2022",
    title: "ISO/IEC 27001:2022 Lead Auditor Course",
    type: "Lead Auditor",
    duration: "5 Days",
    hours: "40 Hrs",
    format: "Online & Classroom",
    passMark: "70%",
    prerequisites: "Basic ISMS understanding, degree/diploma + 3 yrs work experience",
    description: "Master planning, conducting, and reporting 3rd-party ISMS audits against ISO 27001:2022.",
    accreditation: "Exemplar Global Authorised",
    featured: true,
  },
  {
    id: "lead-auditor-9001",
    standardCode: "ISO 9001:2015",
    title: "ISO 9001:2015 Lead Auditor Course",
    type: "Lead Auditor",
    duration: "5 Days",
    hours: "40 Hrs",
    format: "Online & Classroom",
    passMark: "70%",
    prerequisites: "Knowledge of QMS principles, degree/diploma + 3 yrs work experience",
    description: "Comprehensive 40-hour intensive program for lead auditors, management reps, and consultants.",
    accreditation: "Exemplar Global Authorised",
    featured: true,
  },
  {
    id: "internal-auditor-9001",
    standardCode: "ISO 9001:2015",
    title: "ISO 9001:2015 Internal Auditor Course",
    type: "Internal Auditor",
    duration: "2 Days",
    hours: "16 Hrs",
    format: "Online Virtual",
    passMark: "60%",
    prerequisites: "Familiarity with organizational processes",
    description: "Practical training on conducting internal audits, checklist creation, and non-conformity reporting.",
    accreditation: "Exemplar Global Certified",
  },
  {
    id: "lead-auditor-14001",
    standardCode: "ISO 14001:2015",
    title: "ISO 14001:2015 Lead Auditor Course",
    type: "Lead Auditor",
    duration: "5 Days",
    hours: "40 Hrs",
    format: "Online & Classroom",
    passMark: "70%",
    prerequisites: "Basic EMS understanding, degree/diploma + 3 yrs work experience",
    description: "Learn to audit environmental aspects, legal registers, and strategic EMS performance.",
    accreditation: "Exemplar Global Authorised",
  },
  {
    id: "gdpr-dpo-professional",
    standardCode: "GDPR / PIMS",
    title: "Certified Data Protection Officer (DPO)",
    type: "Professional",
    duration: "4 Days",
    hours: "32 Hrs",
    format: "Online Virtual",
    passMark: "50%",
    prerequisites: "2+ years IT, compliance or legal background",
    description: "In-depth DPO training covering GDPR compliance, DPIAs, breach management, and ISO 27701 alignment.",
    accreditation: "B4Q Executive Credential",
  },
  {
    id: "six-sigma-green-belt",
    standardCode: "Lean Six Sigma",
    title: "Six Sigma Green Belt Certification",
    type: "Professional",
    duration: "5 Days",
    hours: "40 Hrs",
    format: "Online & Classroom",
    passMark: "50%",
    prerequisites: "4 years professional experience in operations or engineering",
    description: "DMAIC methodology, statistical tools, root cause analysis, and process optimization.",
    accreditation: "B4Q Process Excellence",
  },
];

export const OFFICE_LOCATIONS: OfficeLocation[] = [
  {
    id: "uk",
    country: "United Kingdom",
    flag: "🇬🇧",
    city: "London",
    address: "71-75 Shelton Street, Covent Garden, London, WC2H 9JQ",
    phone: "+44 7721156196",
    email: "info@b4qm.com",
    localTimezone: "GMT / BST",
  },
  {
    id: "in",
    country: "India",
    flag: "🇮🇳",
    city: "Delhi NCR",
    address: "B-214, Pacific Business Park, Sahibabad, Delhi NCR 201010",
    phone: "+91 8851447640",
    email: "india@b4qm.com",
    localTimezone: "IST (UTC+5:30)",
  },
  {
    id: "us",
    country: "United States",
    flag: "🇺🇸",
    city: "Delaware",
    address: "16192 Coastal Highway, Lewes, Delaware 19958",
    phone: "+1 302 645 7400",
    email: "usa@b4qm.com",
    localTimezone: "EST (UTC-5)",
  },
  {
    id: "sg",
    country: "Singapore",
    flag: "🇸🇬",
    city: "Singapore",
    address: "10 Anson Road, #26-04 International Plaza, Singapore 079903",
    phone: "+65 6223 9888",
    email: "singapore@b4qm.com",
    localTimezone: "SGT (UTC+8)",
  },
];

export const PUBLIC_DOCUMENTS: DocumentItem[] = [
  { id: "doc-a", code: "Doc A", title: "Certification Application Form", category: "Forms & Guidelines", format: "PDF", size: "420 KB", updatedDate: "2026-01-15", downloadUrl: "#" },
  { id: "doc-b", code: "Doc B", title: "Certification Agreement & General Conditions", category: "Policy & Agreement", format: "PDF", size: "1.2 MB", updatedDate: "2026-02-10", downloadUrl: "#" },
  { id: "doc-c", code: "Doc C", title: "Customer Satisfaction Survey Form", category: "Forms & Guidelines", format: "PDF", size: "280 KB", updatedDate: "2025-11-20", downloadUrl: "#" },
  { id: "doc-d", code: "Doc D", title: "Complaints, Appeals & Feedback Procedure", category: "Procedures", format: "PDF", size: "650 KB", updatedDate: "2026-03-01", downloadUrl: "#" },
  { id: "doc-e", code: "Doc E", title: "Certification Process Overview & Lifecycle", category: "Procedures", format: "PDF", size: "890 KB", updatedDate: "2026-01-30", downloadUrl: "#" },
  { id: "doc-f", code: "Doc F", title: "Public Information Request Procedure", category: "Procedures", format: "PDF", size: "340 KB", updatedDate: "2025-10-12", downloadUrl: "#" },
  { id: "doc-g", code: "Doc G", title: "General Terms of Use & Impartiality Policy", category: "Policy & Agreement", format: "PDF", size: "950 KB", updatedDate: "2026-02-28", downloadUrl: "#" },
  { id: "doc-h", code: "Doc H", title: "Certification FAQ & Guidance Sheet", category: "Forms & Guidelines", format: "PDF", size: "510 KB", updatedDate: "2026-03-15", downloadUrl: "#" },
  { id: "doc-j1", code: "Doc J.1", title: "Certification Mark & Logo Regulations", category: "Policy & Agreement", format: "PDF", size: "1.5 MB", updatedDate: "2026-02-05", downloadUrl: "#" },
  { id: "doc-k", code: "Doc K", title: "Granting, Maintaining & Renewing Procedure", category: "Procedures", format: "PDF", size: "780 KB", updatedDate: "2026-01-18", downloadUrl: "#" },
];

export const MOCK_CERTIFICATES: CertificateData[] = [
  {
    certNumber: "B4Q-ISMS-2026-8842",
    clientName: "Apex Global Technologies Ltd.",
    standard: "ISO/IEC 27001:2022 (ISMS)",
    scope: "Design, development, and hosting of enterprise cloud SaaS applications and cyber managed services.",
    country: "United Kingdom",
    issueDate: "2024-03-15",
    expiryDate: "2027-03-14",
    status: "Valid",
    sites: ["London HQ", "Manchester Data Center"],
    type: "Organisation",
  },
  {
    certNumber: "B4Q-QMS-2025-4129",
    clientName: "Vanguard Precision Engineering Pvt. Ltd.",
    standard: "ISO 9001:2015 (QMS)",
    scope: "Manufacture and supply of high-precision CNC components for automotive and aerospace sectors.",
    country: "India",
    issueDate: "2023-08-10",
    expiryDate: "2026-08-09",
    status: "Valid",
    sites: ["Delhi Manufacturing Plant 1", "Pune Assembly Hub"],
    type: "Organisation",
  },
  {
    certNumber: "EG-LA-2026-0091",
    clientName: "Jonathan Vance",
    standard: "Exemplar Global ISO 27001:2022 Lead Auditor",
    scope: "Authorised 3rd-Party ISMS Lead Auditor (Card ID: EG-901422)",
    country: "Singapore",
    issueDate: "2026-01-10",
    expiryDate: "2029-01-09",
    status: "Valid",
    sites: ["Individual Auditor Registration"],
    type: "Personnel",
  },
];
