import { ISOStandard, TrainingCourse, DocumentItem, OfficeLocation, CertificateData } from "@/types";

export const ISO_STANDARDS: ISOStandard[] = [
  {
    id: "iso-9001",
    code: "ISO 9001:2015",
    name: "Quality Management System (QMS)",
    shortName: "QMS ISO 9001",
    category: "Quality & Operations",
    description: "The global benchmark for operational consistency, risk-based process control, and customer satisfaction.",
    outcome: "Boost operational efficiency, client trust & global market access.",
    clauseChip: "§ 4–10 HLS",
    iconName: "ShieldCheck",
    featured: true,
  },
  {
    id: "iso-14001",
    code: "ISO 14001:2026",
    name: "Environmental Management System (EMS)",
    shortName: "EMS ISO 14001",
    category: "Health & Environment",
    description: "Framework for strategic environmental performance, waste reduction, and aspect/impact control.",
    outcome: "Reduce environmental footprint, regulatory risk & resource waste.",
    clauseChip: "§ 4–10 HLS",
    iconName: "Leaf",
    badge: "Updated 2026",
    featured: true,
  },
  {
    id: "iso-45001",
    code: "ISO 45001:2018",
    name: "Occupational Health & Safety (OH&S)",
    shortName: "OH&S ISO 45001",
    category: "Health & Environment",
    description: "Proactive framework for workplace safety, hazard elimination, and worker health management.",
    outcome: "Eliminate hazard risks, reduce absenteeism & safeguard workforce.",
    clauseChip: "§ 4–10 HLS",
    iconName: "Activity",
    featured: true,
  },
  {
    id: "iso-22000",
    code: "ISO 22000:2018",
    name: "Food Safety Management System (FSMS)",
    shortName: "FSMS ISO 22000",
    category: "Food Safety",
    description: "Combines Codex HACCP principles with prerequisite programs for end-to-end food chain safety.",
    outcome: "Ensure food product integrity & legal compliance across supply chains.",
    clauseChip: "HACCP + PRPs",
    iconName: "Utensils",
    featured: true,
  },
  {
    id: "iso-27001",
    code: "ISO/IEC 27001:2022",
    name: "Information Security Management System (ISMS)",
    shortName: "ISMS ISO 27001",
    category: "Information Security & Privacy",
    description: "Modernized 2022 framework with 93 controls & 4 themes protecting digital infrastructure and cloud assets.",
    outcome: "Protect critical data assets, achieve cyber resilience & client compliance.",
    clauseChip: "93 Controls · 4 Themes",
    iconName: "Lock",
    badge: "Updated 2022",
    featured: true,
  },
];

export const COURSES: TrainingCourse[] = [
  {
    id: "lead-auditor-27001",
    standardCode: "ISO 27001:2022",
    title: "ISO/IEC 27001:2022 Lead Auditor Course",
    type: "Lead Auditor",
    duration: "5 Days",
    hours: "40 Hrs",
    format: "Online & Classroom",
    passMark: "70%",
    prerequisites: "Basic ISMS understanding, degree/diploma + 3 yrs work experience",
    description: "Master planning, conducting, and reporting 3rd-party ISMS audits against ISO 27001:2022.",
    accreditation: "Exemplar Global Authorised",
    featured: true,
  },
  {
    id: "lead-auditor-9001",
    standardCode: "ISO 9001:2015",
    title: "ISO 9001:2015 Lead Auditor Course",
    type: "Lead Auditor",
    duration: "5 Days",
    hours: "40 Hrs",
    format: "Online & Classroom",
    passMark: "70%",
    prerequisites: "Knowledge of QMS principles, degree/diploma + 3 yrs work experience",
    description: "Comprehensive 40-hour intensive program for lead auditors, management reps, and consultants.",
    accreditation: "Exemplar Global Authorised",
    featured: true,
  },
  {
    id: "internal-auditor-9001",
    standardCode: "ISO 9001:2015",
    title: "ISO 9001:2015 Internal Auditor Course",
    type: "Internal Auditor",
    duration: "2 Days",
    hours: "16 Hrs",
    format: "Online Virtual",
    passMark: "60%",
    prerequisites: "Familiarity with organizational processes",
    description: "Practical training on conducting internal audits, checklist creation, and non-conformity reporting.",
    accreditation: "Exemplar Global Certified",
  },
  {
    id: "lead-auditor-14001",
    standardCode: "ISO 14001:2026",
    title: "ISO 14001:2026 Lead Auditor Course",
    type: "Lead Auditor",
    duration: "5 Days",
    hours: "40 Hrs",
    format: "Online & Classroom",
    passMark: "70%",
    prerequisites: "Basic EMS understanding, degree/diploma + 3 yrs work experience",
    description: "Learn to audit environmental aspects, legal registers, and strategic EMS performance.",
    accreditation: "Exemplar Global Authorised",
  },
  {
    id: "gdpr-dpo-professional",
    standardCode: "GDPR / PIMS",
    title: "Certified Data Protection Officer (DPO)",
    type: "Professional",
    duration: "4 Days",
    hours: "32 Hrs",
    format: "Online Virtual",
    passMark: "50%",
    prerequisites: "2+ years IT, compliance or legal background",
    description: "In-depth DPO training covering GDPR compliance, DPIAs, breach management, and ISO 27701 alignment.",
    accreditation: "B4Q Executive Credential",
  },
  {
    id: "six-sigma-green-belt",
    standardCode: "Lean Six Sigma",
    title: "Six Sigma Green Belt Certification",
    type: "Professional",
    duration: "5 Days",
    hours: "40 Hrs",
    format: "Online & Classroom",
    passMark: "50%",
    prerequisites: "4 years professional experience in operations or engineering",
    description: "DMAIC methodology, statistical tools, root cause analysis, and process optimization.",
    accreditation: "B4Q Process Excellence",
  },
];

export const OFFICE_LOCATIONS: OfficeLocation[] = [
  {
    id: "in-head",
    country: "India (Head Office)",
    flag: "🇮🇳",
    city: "Delhi NCR (NSP)",
    address: "453, 4th Floor, Aggarwal Metro Height, Netaji Subhash Place (NSP), Pitampura, Delhi-110034, India",
    phone: "098997 15540 / 09899715540",
    email: "info@b4qm.com",
    localTimezone: "IST (UTC+5:30)",
  },
  {
    id: "in-reg",
    country: "India (Registered Office)",
    flag: "🇮🇳",
    city: "Delhi (Narela)",
    address: "2nd Floor, Aman Market, RKBM House, Narela Mandi, Delhi-110040, India",
    phone: "+91 98997 15540",
    email: "info@b4qm.com",
    localTimezone: "IST (UTC+5:30)",
  },
  {
    id: "uk",
    country: "United Kingdom",
    flag: "🇬🇧",
    city: "London",
    address: "82, ADLEY STREET, LONDON E5 0DZ, UK",
    phone: "+44 7721156196",
    email: "info@b4qm.com",
    localTimezone: "GMT / BST",
  },
  {
    id: "us",
    country: "United States",
    flag: "🇺🇸",
    city: "Delaware",
    address: "16192 Coastal Highway, Lewes, Delaware 19958",
    phone: "+1 302 645 7400",
    email: "usa@b4qm.com",
    localTimezone: "EST (UTC-5)",
  },
];

export const CORPORATE_METRICS = [
  { label: "On Time Services", value: "99%", desc: "Prompt audit execution & delivery" },
  { label: "Client Satisfaction", value: "98.5%", desc: "Verified client satisfaction score" },
  { label: "Client Support", value: "99.9%", desc: "Continuous technical & audit support" },
  { label: "Ethical & Impartial Assessment", value: "100%", desc: "Strict ISO/IEC 17021-1 impartiality" }
];

export const PUBLIC_DOCUMENTS: DocumentItem[] = [
  {
    id: "doc-a",
    code: "Doc-A",
    title: "Application Form for Management System Certification",
    category: "Forms & Guidelines",
    format: "PDF",
    size: "420 KB",
    updatedDate: "July 2026",
    downloadUrl: "/docs/Application-Form.pdf",
  },
  {
    id: "doc-b",
    code: "Doc-B",
    title: "Certificate Agreement & Client Proposal Terms",
    category: "Policy & Agreement",
    format: "PDF",
    size: "680 KB",
    updatedDate: "July 2026",
    downloadUrl: "/docs/Certificate-Agreement.pdf",
  },
  {
    id: "doc-c",
    code: "Doc-C",
    title: "Customer Satisfaction Survey Form",
    category: "Forms & Guidelines",
    format: "PDF",
    size: "210 KB",
    updatedDate: "July 2026",
    downloadUrl: "/docs/Customer-Satisfaction-Form.pdf",
  },
  {
    id: "doc-d",
    code: "Doc-D",
    title: "Procedure for Complaints, Appeals & Feedback",
    category: "Procedures",
    format: "PDF",
    size: "510 KB",
    updatedDate: "July 2026",
    downloadUrl: "/docs/Complaints-Appeals-Procedure.pdf",
  },
  {
    id: "doc-g",
    code: "Doc-G",
    title: "General Operating Conditions for Applicants",
    category: "Policy & Agreement",
    format: "PDF",
    size: "590 KB",
    updatedDate: "July 2026",
    downloadUrl: "/docs/General-Conditions.pdf",
  },
  {
    id: "doc-j",
    code: "Doc-J",
    title: "Logo Usage Regulations for Certified Clients",
    category: "Procedures",
    format: "PDF",
    size: "820 KB",
    updatedDate: "July 2026",
    downloadUrl: "/docs/Logo-Usage-Regulations.pdf",
  },
  {
    id: "doc-l",
    code: "Doc-L",
    title: "Statement of Impartiality Policy",
    category: "Policy & Agreement",
    format: "PDF",
    size: "390 KB",
    updatedDate: "July 2026",
    downloadUrl: "/docs/Statement-of-Impartiality-Policy.pdf",
  },
];
