import { ISOStandard, TrainingCourse, DocumentItem, OfficeLocation, CertificateData } from "@/types";

export const ISO_STANDARDS: ISOStandard[] = [
  {
    id: "iso-9001",
    code: "ISO 9001:2015",
    name: "Quality Management System (QMS)",
    shortName: "QMS ISO 9001",
    category: "Quality & Operations",
    description: "The global benchmark for operational consistency, risk-based process control, and customer satisfaction.",
    outcome: "Boost operational efficiency, client trust & global market access.",
    clauseChip: "§ 4–10 HLS",
    iconName: "ShieldCheck",
    featured: true,
  },
  {
    id: "iso-13485",
    code: "ISO 13485:2016",
    name: "Medical Devices QMS",
    shortName: "Medical ISO 13485",
    category: "Medical & Health",
    description: "Quality management system requirements for organizations involved in the medical device lifecycle.",
    outcome: "Ensure regulatory compliance, risk management & patient safety across medical device production.",
    clauseChip: "Medical Device QMS",
    iconName: "HeartPulse",
    featured: true,
  },
  {
    id: "iso-14001",
    code: "ISO 14001:2026",
    name: "Environmental Management System (EMS)",
    shortName: "EMS ISO 14001",
    category: "Health & Environment",
    description: "Framework for strategic environmental performance, waste reduction, and aspect/impact control.",
    outcome: "Reduce environmental footprint, regulatory risk & resource waste.",
    clauseChip: "§ 4–10 HLS",
    iconName: "Leaf",
    badge: "Updated 2026",
    featured: true,
  },
  {
    id: "iso-20000-1",
    code: "ISO/IEC 20000-1:2018",
    name: "IT Service Management System (ITSMS)",
    shortName: "ITSMS ISO 20000-1",
    category: "IT Services",
    description: "Aligns IT services with business objectives across the complete service lifecycle (Plan → Deliver).",
    outcome: "Elevate IT service reliability, SLA compliance & customer satisfaction.",
    clauseChip: "Service Lifecycle",
    iconName: "Server",
    featured: true,
  },
  {
    id: "iso-21001",
    code: "ISO 21001:2025",
    name: "Educational Organization Management System (EOMS)",
    shortName: "EOMS ISO 21001",
    category: "Education & Learning",
    description: "Requirements for educational organizations to support acquisition of competence through teaching and research.",
    outcome: "Elevate learner satisfaction, institutional quality & academic governance.",
    clauseChip: "EOMS Framework",
    iconName: "BookOpen",
  },
  {
    id: "iso-22000",
    code: "ISO 22000:2018",
    name: "Food Safety Management System (FSMS)",
    shortName: "FSMS ISO 22000",
    category: "Food Safety",
    description: "Combines Codex HACCP principles with prerequisite programs for end-to-end food chain safety.",
    outcome: "Ensure food product integrity & legal compliance across supply chains.",
    clauseChip: "HACCP + PRPs",
    iconName: "Utensils",
    featured: true,
  },
  {
    id: "iso-27001",
    code: "ISO/IEC 27001:2022",
    name: "Information Security Management System (ISMS)",
    shortName: "ISMS ISO 27001",
    category: "Information Security & Privacy",
    description: "Modernized 2022 framework with 93 controls & 4 themes protecting digital infrastructure and cloud assets.",
    outcome: "Protect critical data assets, achieve cyber resilience & client compliance.",
    clauseChip: "93 Controls · 4 Themes",
    iconName: "Lock",
    badge: "Updated 2022",
    featured: true,
  },
  {
    id: "iso-27701",
    code: "ISO/IEC 27701:2025",
    name: "Privacy Information Management System (PIMS)",
    shortName: "PIMS ISO 27701",
    category: "Information Security & Privacy",
    description: "Privacy extension to ISO 27001/27002 establishing PIMS controls for personal data protection.",
    outcome: "Demonstrate GDPR, DPA & global privacy regulation compliance.",
    clauseChip: "GDPR PIMS Annex",
    iconName: "UserCheck",
  },
  {
    id: "iso-50001",
    code: "ISO 50001:2018",
    name: "Energy Management System (EnMS)",
    shortName: "EnMS ISO 50001",
    category: "Energy & Sustainability",
    description: "Structured framework to optimize energy performance, reduce carbon emissions, and cut utility costs.",
    outcome: "Lower energy intensity, operational expense & carbon footprint.",
    clauseChip: "EnMS Baseline",
    iconName: "Zap",
  },
  {
    id: "ce-marking",
    code: "CE Marking",
    name: "European Conformity Marking",
    shortName: "CE Conformity",
    category: "Product Conformity",
    description: "Product conformity assessment enabling free movement of goods within the European Economic Area.",
    outcome: "Access EU single market with verified safety & statutory compliance.",
    clauseChip: "EU Directives",
    iconName: "Globe",
    featured: true,
  },
  {
    id: "soc-services",
    code: "SOC 1, 2, 3",
    name: "Service Organization Control Reports",
    shortName: "SOC Audit Reports",
    category: "Security & Controls",
    description: "SSAE 18 & Trust Services Criteria evaluation covering Financial, Security, Availability & Privacy controls.",
    outcome: "Provide enterprise clients with independent SOC 1 / SOC 2 Type II audit reports.",
    clauseChip: "SSAE 18 / TSC",
    iconName: "ShieldAlert",
    featured: true,
  },
  {
    id: "vendor-assessment",
    code: "Vendor Assessment",
    name: "Supplier & Vendor Validation",
    shortName: "Vendor Validation",
    category: "Supply Chain",
    description: "Independent vendor validation confirming supplier legitimacy, financial stability, and regulatory compliance.",
    outcome: "Mitigate supply chain risk & protect against non-compliant vendors.",
    clauseChip: "Third-Party Audit",
    iconName: "Building",
  },
  {
    id: "iso-45001",
    code: "ISO 45001:2018",
    name: "Occupational Health & Safety (OH&S)",
    shortName: "OH&S ISO 45001",
    category: "Health & Environment",
    description: "Proactive framework for workplace safety, hazard elimination, and worker health management.",
    outcome: "Eliminate hazard risks, reduce absenteeism & safeguard workforce.",
    clauseChip: "§ 4–10 HLS",
    iconName: "Activity",
    featured: true,
  },
  {
    id: "iso-29993",
    code: "ISO 29993:2017",
    name: "Learning Services Outside Formal Education",
    shortName: "ISO 29993 Learning",
    category: "Education & Learning",
    description: "Requirements for non-formal learning service providers including vocational and corporate training.",
    outcome: "Demonstrate high learning outcome evaluation & structured instruction.",
    clauseChip: "LSP Criteria",
    iconName: "Award",
  },
  {
    id: "iso-22002-4",
    code: "ISO 22002-4:2025",
    name: "Prerequisite Programs — Food Packaging",
    shortName: "ISO 22002-4 PRPs",
    category: "Food Safety",
    description: "Prerequisite programmes for food safety in the manufacture of food and feed packaging.",
    outcome: "Maintain hygienic conditions and prevent packaging contamination.",
    clauseChip: "Food-Contact PRPs",
    iconName: "Box",
  },
  {
    id: "iso-10002",
    code: "ISO 10002:2018",
    name: "Customer Complaints Handling",
    shortName: "ISO 10002 Complaints",
    category: "Customer Excellence",
    description: "Guidance for establishing and maintaining an effective, systematic complaints-handling process.",
    outcome: "Turn customer feedback into continual management system improvements.",
    clauseChip: "Feedback Loop",
    iconName: "MessageSquare",
  },
  {
    id: "iso-10004",
    code: "ISO 10004:2018",
    name: "Customer Satisfaction Monitoring",
    shortName: "ISO 10004 CSAT",
    category: "Customer Excellence",
    description: "Processes to measure, monitor, and analyze customer satisfaction metrics and trend identification.",
    outcome: "Drive evidence-based decision making to elevate client retention.",
    clauseChip: "CSAT Analytics",
    iconName: "BarChart3",
  },
  {
    id: "iso-15378",
    code: "ISO 15378:2017",
    name: "Medicinal Packaging Materials QMS",
    shortName: "Pharma Packaging QMS",
    category: "Medical & Health",
    description: "Combines ISO 9001 with Good Manufacturing Practice (GMP) for primary medicinal packaging.",
    outcome: "Guarantee primary packaging sterility and pharmaceutical compliance.",
    clauseChip: "ISO 9001 + GMP",
    iconName: "PackageCheck",
  },
  {
    id: "iso-22716",
    code: "ISO 22716:2007",
    name: "Cosmetics — Good Manufacturing Practices (GMP)",
    shortName: "Cosmetics GMP",
    category: "Quality & Operations",
    description: "Guidelines for production, control, storage, and shipment of cosmetic products under GMP.",
    outcome: "Ensure cosmetic product safety, batch purity, and global market access.",
    clauseChip: "Cosmetic GMP",
    iconName: "Sparkles",
  },
  {
    id: "iso-22301",
    code: "ISO 22301:2019",
    name: "Business Continuity Management System (BCMS)",
    shortName: "BCMS ISO 22301",
    category: "Business Resilience",
    description: "Framework to plan, implement, and maintain business continuity against operational disruptions.",
    outcome: "Ensure rapid operational recovery during crises, outages, or disasters.",
    clauseChip: "BIA & Recovery",
    iconName: "RefreshCw",
    featured: true,
  },
  {
    id: "iso-25000",
    code: "ISO/IEC 25000:2014",
    name: "Software Quality Requirements & Evaluation (SQuaRE)",
    shortName: "SQuaRE ISO 25000",
    category: "IT Services",
    description: "Framework for specifying and evaluating software product quality requirements.",
    outcome: "Validate software product architecture, reliability, and usability.",
    clauseChip: "SQuaRE Model",
    iconName: "Code",
  },
  {
    id: "iso-21827",
    code: "ISO/IEC 21827:2008",
    name: "Systems Security Engineering (SSE-CMM)",
    shortName: "SSE-CMM Security",
    category: "Information Security & Privacy",
    description: "Capability Maturity Model for assessing security engineering processes.",
    outcome: "Evaluate and advance security engineering process maturity.",
    clauseChip: "CMM Maturity",
    iconName: "Shield",
  },
  {
    id: "iso-27017",
    code: "ISO/IEC 27017:2026",
    name: "Cloud Services Security Controls",
    shortName: "Cloud ISO 27017",
    category: "Information Security & Privacy",
    description: "Guidelines for information security controls applicable to cloud service providers and customers.",
    outcome: "Clarify shared cloud security responsibilities across public/private clouds.",
    clauseChip: "Cloud Controls",
    iconName: "Cloud",
  },
  {
    id: "iso-27018",
    code: "ISO/IEC 27018:2025",
    name: "Protection of PII in Public Clouds",
    shortName: "PII Cloud ISO 27018",
    category: "Information Security & Privacy",
    description: "Controls for cloud service providers processing personally identifiable information (PII).",
    outcome: "Protect customer personal data in public clouds and comply with GDPR.",
    clauseChip: "PII Protection",
    iconName: "Lock",
  },
  {
    id: "vapt-services",
    code: "VAPT Testing",
    name: "Vulnerability Assessment & Penetration Testing",
    shortName: "VAPT Testing",
    category: "IT Services",
    description: "Comprehensive security services identifying network, server, and application vulnerabilities.",
    outcome: "Harden cyber infrastructure against real-world breach vectors.",
    clauseChip: "VA + PT Audit",
    iconName: "Terminal",
    featured: true,
  },
  {
    id: "sa-8000",
    code: "SA 8000:2026",
    name: "Social Accountability Management",
    shortName: "SA8000 Social",
    category: "Social Accountability",
    description: "Voluntary standard for decent, ethical working conditions across global supply chains.",
    outcome: "Demonstrate ethical treatment of workers, fair wages, and labor compliance.",
    clauseChip: "Labor Rights",
    iconName: "Users",
  },
  {
    id: "as-9100",
    code: "AS 9100",
    name: "Aerospace Quality Management System",
    shortName: "AS 9100 Aerospace",
    category: "Quality & Operations",
    description: "Aerospace industry quality standard incorporating ISO 9001 with flight-critical controls.",
    outcome: "Gain vendor qualification for commercial & defense aerospace tenders.",
    clauseChip: "Aerospace QMS",
    iconName: "Plane",
  },
  {
    id: "iso-15189",
    code: "ISO 15189:2022",
    name: "Medical Laboratories Quality & Competence",
    shortName: "Medical Lab ISO 15189",
    category: "Medical & Health",
    description: "Requirements for quality and technical competence in clinical and diagnostic medical laboratories.",
    outcome: "Verify clinical laboratory testing accuracy and diagnostic competence.",
    clauseChip: "Lab Competence",
    iconName: "Microscope",
  },
  {
    id: "iso-26000",
    code: "ISO 26000:2010",
    name: "Guidance on Social Responsibility",
    shortName: "ISO 26000 CSR",
    category: "Social Accountability",
    description: "International guidance to help organizations translate social responsibility principles into action.",
    outcome: "Structure CSR governance, environmental stewardship, and community impact.",
    clauseChip: "CSR Guidance",
    iconName: "Globe",
  }
];

export const COURSES: TrainingCourse[] = [
  {
    id: "lead-auditor-27001",
    standardCode: "ISO 27001:2022",
    title: "ISO/IEC 27001:2022 Lead Auditor Course",
    type: "Lead Auditor",
    duration: "5 Days",
    hours: "40 Hrs",
    format: "Online & Classroom",
    passMark: "70%",
    prerequisites: "Basic ISMS understanding, degree/diploma + 3 yrs work experience",
    description: "Master planning, conducting, and reporting 3rd-party ISMS audits against ISO 27001:2022.",
    accreditation: "Exemplar Global Authorised",
    featured: true,
  },
  {
    id: "lead-auditor-9001",
    standardCode: "ISO 9001:2015",
    title: "ISO 9001:2015 Lead Auditor Course",
    type: "Lead Auditor",
    duration: "5 Days",
    hours: "40 Hrs",
    format: "Online & Classroom",
    passMark: "70%",
    prerequisites: "Knowledge of QMS principles, degree/diploma + 3 yrs work experience",
    description: "Comprehensive 40-hour intensive program for lead auditors, management reps, and consultants.",
    accreditation: "Exemplar Global Authorised",
    featured: true,
  },
  {
    id: "internal-auditor-9001",
    standardCode: "ISO 9001:2015",
    title: "ISO 9001:2015 Internal Auditor Course",
    type: "Internal Auditor",
    duration: "2 Days",
    hours: "16 Hrs",
    format: "Online Virtual",
    passMark: "60%",
    prerequisites: "Familiarity with organizational processes",
    description: "Practical training on conducting internal audits, checklist creation, and non-conformity reporting.",
    accreditation: "Exemplar Global Certified",
  },
  {
    id: "lead-auditor-14001",
    standardCode: "ISO 14001:2026",
    title: "ISO 14001:2026 Lead Auditor Course",
    type: "Lead Auditor",
    duration: "5 Days",
    hours: "40 Hrs",
    format: "Online & Classroom",
    passMark: "70%",
    prerequisites: "Basic EMS understanding, degree/diploma + 3 yrs work experience",
    description: "Learn to audit environmental aspects, legal registers, and strategic EMS performance.",
    accreditation: "Exemplar Global Authorised",
  },
  {
    id: "gdpr-dpo-professional",
    standardCode: "GDPR / PIMS",
    title: "Certified Data Protection Officer (DPO)",
    type: "Professional",
    duration: "4 Days",
    hours: "32 Hrs",
    format: "Online Virtual",
    passMark: "50%",
    prerequisites: "2+ years IT, compliance or legal background",
    description: "In-depth DPO training covering GDPR compliance, DPIAs, breach management, and ISO 27701 alignment.",
    accreditation: "B4Q Executive Credential",
  },
  {
    id: "six-sigma-green-belt",
    standardCode: "Lean Six Sigma",
    title: "Six Sigma Green Belt Certification",
    type: "Professional",
    duration: "5 Days",
    hours: "40 Hrs",
    format: "Online & Classroom",
    passMark: "50%",
    prerequisites: "4 years professional experience in operations or engineering",
    description: "DMAIC methodology, statistical tools, root cause analysis, and process optimization.",
    accreditation: "B4Q Process Excellence",
  },
];

export const OFFICE_LOCATIONS: OfficeLocation[] = [
  {
    id: "in-head",
    country: "India (Head Office)",
    flag: "🇮🇳",
    city: "Delhi NCR (NSP)",
    address: "453, 4th Floor, Aggarwal Metro Height, Netaji Subhash Place (NSP), Pitampura, Delhi-110034, India",
    phone: "098997 15540 / 09899715540",
    email: "info@b4qm.com",
    localTimezone: "IST (UTC+5:30)",
  },
  {
    id: "in-reg",
    country: "India (Registered Office)",
    flag: "🇮🇳",
    city: "Delhi (Narela)",
    address: "2nd Floor, Aman Market, RKBM House, Narela Mandi, Delhi-110040, India",
    phone: "+91 98997 15540",
    email: "info@b4qm.com",
    localTimezone: "IST (UTC+5:30)",
  },
  {
    id: "uk",
    country: "United Kingdom",
    flag: "🇬🇧",
    city: "London",
    address: "82, ADLEY STREET, LONDON E5 0DZ, UK",
    phone: "+44 7721156196",
    email: "info@b4qm.com",
    localTimezone: "GMT / BST",
  },
  {
    id: "us",
    country: "United States",
    flag: "🇺🇸",
    city: "Delaware",
    address: "16192 Coastal Highway, Lewes, Delaware 19958",
    phone: "+1 302 645 7400",
    email: "usa@b4qm.com",
    localTimezone: "EST (UTC-5)",
  },
];

export const CORPORATE_METRICS = [
  { label: "On Time Services", value: "99%", desc: "Prompt audit execution & delivery" },
  { label: "Client Satisfaction", value: "98.5%", desc: "Verified client satisfaction score" },
  { label: "Client Support", value: "99.9%", desc: "Continuous technical & audit support" },
  { label: "Ethical & Impartial Assessment", value: "100%", desc: "Strict ISO/IEC 17021-1 impartiality" }
];

export const PUBLIC_DOCUMENTS: DocumentItem[] = [
  {
    id: "doc-a",
    code: "Doc-A",
    title: "Application Form for Management System Certification",
    category: "Forms & Guidelines",
    format: "PDF",
    size: "420 KB",
    updatedDate: "July 2026",
    downloadUrl: "/docs/Application-Form.pdf",
  },
  {
    id: "doc-b",
    code: "Doc-B",
    title: "Certificate Agreement & Client Proposal Terms",
    category: "Policy & Agreement",
    format: "PDF",
    size: "680 KB",
    updatedDate: "July 2026",
    downloadUrl: "/docs/Certificate-Agreement.pdf",
  },
  {
    id: "doc-c",
    code: "Doc-C",
    title: "Customer Satisfaction Survey Form",
    category: "Forms & Guidelines",
    format: "PDF",
    size: "210 KB",
    updatedDate: "July 2026",
    downloadUrl: "/docs/Customer-Satisfaction-Form.pdf",
  },
  {
    id: "doc-d",
    code: "Doc-D",
    title: "Procedure for Complaints, Appeals & Feedback",
    category: "Procedures",
    format: "PDF",
    size: "510 KB",
    updatedDate: "July 2026",
    downloadUrl: "/docs/Complaints-Appeals-Procedure.pdf",
  },
  {
    id: "doc-g",
    code: "Doc-G",
    title: "General Operating Conditions for Applicants",
    category: "Policy & Agreement",
    format: "PDF",
    size: "590 KB",
    updatedDate: "July 2026",
    downloadUrl: "/docs/General-Conditions.pdf",
  },
  {
    id: "doc-j",
    code: "Doc-J",
    title: "Logo Usage Regulations for Certified Clients",
    category: "Procedures",
    format: "PDF",
    size: "820 KB",
    updatedDate: "July 2026",
    downloadUrl: "/docs/Logo-Usage-Regulations.pdf",
  },
  {
    id: "doc-l",
    code: "Doc-L",
    title: "Statement of Impartiality Policy",
    category: "Policy & Agreement",
    format: "PDF",
    size: "390 KB",
    updatedDate: "July 2026",
    downloadUrl: "/docs/Statement-of-Impartiality-Policy.pdf",
  },
];
